name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login-dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-and-push-v13
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: seeeverything/pre-commit:terraform-0.13
          build-args: TERRAFORM_VERSION=0.13.7
      - name: build-and-push-v15
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: seeeverything/pre-commit:terraform-0.15
          build-args: TERRAFORM_VERSION=0.15.4
  bump-version:
    needs: [docker]
    name: bump-version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: checkout
      uses: actions/checkout@v2     
    - name: bump-version
      uses: seeeverything/github-tag-action@1.35.0
      env:
        GITHUB_TOKEN: ${{ secrets.DEVOPSBOT_GITHUB_TOKEN }}
        BRANCH: master
        DEFAULT_BUMP: patch
